# Generated by Django 5.1.5 on 2025-02-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0003_event_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='completed',
        ),
    ]
