# Generated by Django 5.1.2 on 2025-02-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_schedule_diary_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='subjects',
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.JSONField(default=dict),
        ),
    ]
