# Generated by Django 5.1.2 on 2025-02-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_remove_student_subjects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='student',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='Diary',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
